In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

1D Array Slicing

In [4]:
arr = np.arange(1,10)
print(arr)
print("Basic slicing: ", arr[2:7])
print("Slice with step: ", arr[1:8:2])
print("Negative index: ", arr[-4])

[1 2 3 4 5 6 7 8 9]
Basic slicing:  [3 4 5 6 7]
Slice with step:  [2 4 6 8]
Negative index:  6


2D Array Slicing

In [9]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr_2d)
print("Specific element: ",arr_2d[1, 2])
print("Entire Row: ", arr_2d[1,:])
print("Entire Column: ", arr_2d[:, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  6
Entire Row:  [4 5 6]
Entire Column:  [3 6 9]


Sorting

In [15]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 3, 2, 6, 7, 6])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsort = np.array([[3,1], [1,2], [2,3]])
print("sorted 2d array by column: ", np.sort(arr_2d_unsort, axis=0))
print("sorted 2d array by row: ", np.sort(arr_2d_unsort, axis=1))

Sorted array:  [1 1 2 3 3 4 5 6 6 7 9]
sorted 2d array by column:  [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row:  [[1 3]
 [1 2]
 [2 3]]


Filter

In [ ]:
#Print even numbers in a array
num = np.arange(1, 11)
print(num)
even = num[num % 2 == 0]
print(even)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


Filter with Mask

In [22]:
mask = num > 5
print("Numbers greater than 5: ", num[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


Fancy Indexing vs np.where()

In [27]:
indices = [0,2,4]
print(num[indices])

where_res = np.where(num>5)
print(where_res)
print("NP where:", num[where_res])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [42]:
condition_array = np.where(num>5, num*4, num*2)    #(condition, x, y)
print(condition_array)

# if(num > 5){
#     num*4
# }else{
#     num*2
# }

condition_array = np.where(num>5, True, False)    #(condition, x, y)
print(condition_array)

[ 2  4  6  8 10 24 28 32 36 40]
[False False False False False  True  True  True  True  True]


Adding and removing the data

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add = arr1+arr2
print("After adding: ",add)

comb = np.concatenate((arr1, arr2))
print(comb)

After adding:  [5 7 9]
[1 2 3 4 5 6]


Array Compatibility

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9, 10])

print("Compatibility Shapes: ", a.shape==b.shape)
print("Compatibility Shapes: ", a.shape==c.shape)

Compatibility Shapes:  True
Compatibility Shapes:  False


In [58]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))    #vstack adds a new row
print(original)
print("\n Vstack: ",with_new_row)

print("\n",original)
new_col = np.array([[5], [10]])
with_new_col = np.hstack((original, new_col))
print("\nHstack: ",with_new_col)


[[1 2]
 [3 4]]

 Vstack:  [[1 2]
 [3 4]
 [5 6]]

 [[1 2]
 [3 4]]

Hstack:  [[ 1  2  5]
 [ 3  4 10]]


Delete Ops

In [60]:
arr = np.array([1,2,3,4,5])
delete = np.delete(arr, 2)
print(delete)  #return the array after deletion

[1 2 4 5]


Maths

In [66]:
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([1,2,6,8,9])

print("addition: ", vec1+vec2)
print("Multiply: ", vec1*vec2)

print("Dot product: ", np.dot(vec1, vec2))

angle = np.arccos(np.dot(vec1, vec2)/(np.linalg.norm(vec1) * np.linalg.norm(vec2)))
print("cos of angle between the two lines is : ", angle)

addition:  [ 2  4  9 12 14]
Multiply:  [ 1  4 18 32 45]
Dot product:  100
cos of angle between the two lines is :  0.1505105877034758


Vectorize

In [67]:
res_types = np.array(['biriyani', 'tea', 'pizza', 'coffee'])
vectorized_upper = np.vectorize(str.upper)

print("vectorized Upper: ", vectorized_upper(res_types))

vectorized Upper:  ['BIRIYANI' 'TEA' 'PIZZA' 'COFFEE']


Broadcast