In [8]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   - -------------------------------------- 0.5/12.8 MB 1.9 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/12.8 MB 360.8 kB/s eta 0:00:34
   -- ------------------------------------- 0.8/12.8 MB 360.8 kB/s eta 0:00:34
   -- ------------------------------------- 0.8/12.8 MB 360.8 kB/s eta 0:00:34
   -- ------------------------------------- 0.8/12.8 MB 360.8 kB/s eta 0:00:34
   -- ------------------------------------- 0.8/12.8 MB 360.8 kB/s eta 0:00:34
   


[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3], [4,5,6]])
print(arr1)
print("2d array:", arr2)

[1 2 3]
2d array: [[1 2 3]
 [4 5 6]]


List vs Numpy

In [12]:
py_list = [1, 2, 3, 4]
print("list multipy by 2: ", py_list*2)

np_arr = np.array([1, 2, 3, 4])
print("array multipy by 2: ", np_arr*2)


list multipy by 2:  [1, 2, 3, 4, 1, 2, 3, 4]
array multipy by 2:  [2 4 6 8]


In [15]:
import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("List operation time:", time.time()-start)

start = time.time()
np_array=np.arange(1,100000)*2
print("Array operation time:", time.time()-start)

List operation time: 0.015524864196777344
Array operation time: 0.0010097026824951172


Creating Array from scratch

In [22]:
zeros = np.zeros((3, 4))  #row, col
print(zeros)

ones = np.ones((2, 3))
print("\n",ones)

print("\n")
full = np.full((2, 5), 7)
print(full)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]


[[7 7 7 7 7]
 [7 7 7 7 7]]


In [34]:
random = np.random.random((2, 3))
print(random)
print("\n")
sequence = np.arange(0,11,2)
print("Sequence array:",sequence)

[[0.36131101 0.33410801 0.50013095]
 [0.99309196 0.5813784  0.48883513]]


Sequence array: [ 0  2  4  6  8 10]


Vector, Matrix and Tensor

In [41]:
vector = np.array([1,2,3])
print("Vector:",vector)
print("\n")
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)
print("\n")

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor: ", tensor)

Vector: [1 2 3]


Matrix:  [[1 2 3]
 [4 5 6]]


Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [45]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print("\n")
print("shape: ", arr.shape)
print("dimension: ", arr.ndim)   
print("Size: ", arr.size)     #no of elements
print("Dtype: ", arr.dtype)  #data type

[[1 2 3]
 [4 5 6]]


shape:  (2, 3)
dimension:  2
Size:  6
Dtype:  int64


Array Reshaping

In [53]:
arr = np.arange(12)
print("original array", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array:",reshaped)

flattened = reshaped.flatten()
print("\nFlattended array: ", flattened)

# ravel returns view instead of copy
raveled = reshaped.ravel()
print("\n Raveled array: ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed array: ", transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattended array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [54]:
arr = np.array([1,2,4,6])
print(np.flip(arr))

[6 4 2 1]
